travis:
  secure:
    BINSTAR_TOKEN: BXnEFWwU3kIN1ZEPs5PVoFDUces8RgfLICoAl8z2bHyxD+HQMx+4f+NBRoqD6t9NJs/VtTCIwdz4h4dDQoIUYd+Hv+zrS2ez+lNJNVtpfVZD8eDnfDvcLql6OnO2rkuJHRvISgNVa+YkaynmtBnD6hOqn7BP30FbhuTo1iXDPvmB6oVobnkpf3qjeV0yewMoiQF8KjOUkdOaetsomPqgpuy1b8oBZOJJUPELh6opGKrwH0bkVk6ONSm7h5YdWq9q5DTDaxQpA0oHmA4s79TYc4bvg4WsE1Pp3YNGbTdScKmNW10rVyQuHpkrcV6JrdfWLlRDPCzmOhu08Ky57exkJb4eC03I+N3DR9d5ov/sNRrLJYSbG3MU6gZdjJXYrflAubr0Z1mw5E5Zrv1VGilpNFO7Yv8oUBypOhH4tPcSmqbqD3twyoYaj0BUrf7/PpYApkIMw/ugI8y9dxqIrONatXleddJ1HebYTI9JWpq4MGsdz4XnJAFEyJzMOxPF/lextPmGnBn+gFLVWuqBvoqeqTA7BW04xLPBt7DiIgnjycT9N/5ELwjV/t/D1PrIGfHuOknmGm3McyizNx+Y2GRaVWubVpzi0H6399JwJcfrRMTMimSa8Ds23nqdrP3pGULu+xlhiYeHbju6GI0OV9FYXKk/xLLB+lue/yHKVd5/OBU=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
